export const TENANTS = [
  {
    organisationCode: '230',
    secureConnectId: 'unused',
    municipalityId: '230',
    historyMunicipalityId: '10347',
    cantonAbbreviation: 'TE',
    organisationName: 'Winterthur',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '230',
  },
  {
    organisationCode: '3443',
    secureConnectId: 'unused',
    municipalityId: '3443',
    historyMunicipalityId: '14466',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Gossau (SG)',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3443',
  },
  {
    organisationCode: 'v_PER2218ZWEI',
    secureConnectId: 'unused',
    organisationName: 'Testing PER-2218 Teil 2',
    organisationTypeCode: '4',
    groupOrganisations: ['541', '543', '743', '931', '868'],
    masterDataId: 'v_PER2218ZWEI',
  },
  {
    organisationCode: '743',
    secureConnectId: 'unused',
    municipalityId: '743',
    historyMunicipalityId: '15249',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Nidau',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '743',
  },
  {
    organisationCode: '543',
    secureConnectId: 'unused',
    municipalityId: '543',
    historyMunicipalityId: '15122',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Mattstetten',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '543',
  },
  {
    organisationCode: '868',
    secureConnectId: 'unused',
    municipalityId: '868',
    historyMunicipalityId: '15120',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Jaberg',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '868',
  },
  {
    organisationCode: '541',
    secureConnectId: 'unused',
    municipalityId: '541',
    historyMunicipalityId: '15120',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Iffwil',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '541',
  },
  {
    organisationCode: '931',
    secureConnectId: 'unused',
    municipalityId: '931',
    historyMunicipalityId: '15329',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Homberg',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '931',
  },
  {
    organisationCode: 'v_PER2218',
    secureConnectId: 'unused',
    organisationName: 'Testing PER-2218 Filter',
    organisationTypeCode: '4',
    groupOrganisations: ['792', '331', '667', '869', '905'],
    masterDataId: 'v_PER2218',
  },
  {
    organisationCode: '792',
    secureConnectId: 'unused',
    municipalityId: '792',
    historyMunicipalityId: '15276',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Lenk',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '792',
  },
  {
    organisationCode: '869',
    secureConnectId: 'unused',
    municipalityId: '869',
    historyMunicipalityId: '15293',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Kaufdorf',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '869',
  },
  {
    organisationCode: '331',
    secureConnectId: 'unused',
    municipalityId: '331',
    historyMunicipalityId: '15015',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Lotzwil',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '331',
  },
  {
    organisationCode: '667',
    secureConnectId: 'unused',
    municipalityId: '667',
    historyMunicipalityId: '15201',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Laupen',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '667',
  },
  {
    organisationCode: '905',
    secureConnectId: 'unused',
    municipalityId: '905',
    historyMunicipalityId: '15315',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Rüderswil',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '905',
  },
  {
    organisationCode: 'v_7_191',
    secureConnectId: 'unused',
    organisationName: 'Test Verbund Dübendorf & Knonau',
    organisationTypeCode: '4',
    groupOrganisations: ['191', '7'],
    masterDataId: 'v_7_191',
  },
  {
    organisationCode: 'v_7_250',
    secureConnectId: 'unused',
    organisationName: 'Test Verbund Knonau & Urdorf',
    organisationTypeCode: '4',
    groupOrganisations: ['250', '7'],
    masterDataId: 'v_7_250',
  },
  {
    organisationCode: '191',
    secureConnectId: '177787361789412132',
    municipalityId: '191',
    historyMunicipalityId: '12205',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Dübendorf',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '191',
  },
  {
    organisationCode: '250',
    secureConnectId: '177787363332850468',
    municipalityId: '250',
    historyMunicipalityId: '13698',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Urdorf',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '250',
  },
  {
    organisationCode: '7',
    secureConnectId: '179668577597523335',
    municipalityId: '7',
    historyMunicipalityId: '12674',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Knonau',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '7',
  },
  {
    organisationCode: '3291',
    secureConnectId: '9999',
    municipalityId: '3291',
    historyMunicipalityId: '14411',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Bad Ragaz',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3291',
  },
  {
    organisationCode: '9999',
    secureConnectId: '177787363416802084',
    municipalityId: '9999',
    historyMunicipalityId: '9999',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Wartau',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '9999',
  },
  {
    organisationCode: '3204',
    secureConnectId: '177787363567731492',
    municipalityId: '3204',
    historyMunicipalityId: '14381',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Wittenbach',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3204',
  },
  {
    organisationCode: '3214',
    secureConnectId: '177787362644984612',
    municipalityId: '3214',
    historyMunicipalityId: '14385',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Mörschwil',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3214',
  },
  {
    organisationCode: '3341',
    secureConnectId: '177787362007319332',
    municipalityId: '3341',
    historyMunicipalityId: '15605',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Gommiswald',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3341',
  },
  {
    organisationCode: '3427',
    secureConnectId: '177787363517268772',
    municipalityId: '3427',
    historyMunicipalityId: '15610',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Wil (SG)',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3427',
  },
  {
    organisationCode: '3359',
    secureConnectId: '177787363550823204',
    municipalityId: '3359',
    historyMunicipalityId: '15381',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Wildhaus-Alt St. Johann',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3359',
  },
  {
    organisationCode: '3352',
    secureConnectId: '177787361806123812',
    municipalityId: '3352',
    historyMunicipalityId: '14435',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Ebnat-Kappel',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3352',
  },
  {
    organisationCode: '3360',
    secureConnectId: '177787362678539044',
    municipalityId: '3360',
    historyMunicipalityId: '15607',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Nesslau',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3360',
  },
  {
    organisationCode: '3408',
    secureConnectId: '177787363366273828',
    municipalityId: '3408',
    historyMunicipalityId: '14457',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Uzwil',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3408',
  },
  {
    organisationCode: '3392',
    secureConnectId: '177787362510832420',
    municipalityId: '3392',
    historyMunicipalityId: '14448',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Kirchberg',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3392',
  },
  {
    organisationCode: '2701',
    secureConnectId: '250140475732788747',
    municipalityId: '2701',
    historyMunicipalityId: '11693',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Basel',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '2701',
  },
  {
    organisationCode: '53',
    secureConnectId: '177787361738883876',
    municipalityId: '53',
    historyMunicipalityId: '11461',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Bülach',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '53',
  },
  {
    organisationCode: '14',
    secureConnectId: '177787363483714340',
    municipalityId: '14',
    historyMunicipalityId: '13255',
    cantonAbbreviation: 'TE',
    organisationName: 'Test Wettswil am Albis',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '14',
  },
  {
    organisationCode: '3203',
    secureConnectId: '177778113466336028',
    municipalityId: '3203',
    historyMunicipalityId: '14380',
    cantonAbbreviation: 'TE',
    organisationName: 'Test St. Gallen',
    organisationTypeCode: '1',
    groupOrganisations: [],
    masterDataId: '3203',
  },
  {
    organisationCode: 'CH',
    secureConnectId: 'XXXCH',
    organisationName: 'Schweiz',
    organisationTypeCode: '3',
    groupOrganisations: [],
    masterDataId: 'CH',
  },
  {
    organisationCode: 'TE',
    secureConnectId: '470008100049421093',
    cantonAbbreviation: 'TE',
    organisationName: 'Kanton TE',
    organisationTypeCode: '4',
    groupOrganisations: [
      '3443',
      '9999',
      '3203',
      '3214',
      '3204',
      '14',
      '3359',
      '3427',
      '2701',
      '3408',
      '191',
      '250',
      '792',
      '331',
      '541',
      '543',
      '743',
      '7',
      '931',
      '667',
      '3291',
      '3392',
      '868',
      '3360',
      '869',
      '3341',
      '3352',
      '53',
      '905',
    ],
    masterDataId: 'TE',
  },
];

export const PERMISSIONS = { accessToInactiveResidents: true, historicValues: true };

export const SIMPLE_SEARCH_SINGLE_PERSON = {
  result: {
    pageSize: 60,
    totalItems: 1,
    offset: 0,
    totalPages: 1,
    pageNumber: 0,
    items: [
      {
        perId: '16773e1a9b28a8120fdbfadf3ac2515e',
        sexCode: {
          type: 'Value',
          value: '1',
        },
        callName: {
          type: 'Value',
          value: 'Contactdata Ersterfassung Und Redelivery',
        },
        name: {
          type: 'Value',
          value: 'Movein',
        },
        allianceName: {
          type: 'Value',
        },
        dateOfBirth: {
          type: 'Value',
          value: '1933-08-01',
        },
        address: {
          egid: {
            type: 'Value',
            value: 190193081,
          },
          ewid: {
            type: 'Value',
            value: 3,
          },
          householdId: {
            type: 'Value',
            value: '190193081/3',
          },
          address: {
            addressLine1: {
              type: 'Value',
            },
            addressLine2: {
              type: 'Value',
            },
            street: {
              type: 'Value',
              value: 'Krüsistr.',
            },
            houseNumber: {
              type: 'Value',
              value: '8',
            },
            dwellingNumber: {
              type: 'Value',
              value: '3',
            },
            locality: {
              type: 'Value',
            },
            town: {
              type: 'Value',
              value: 'St. Gallen',
            },
            swissZipCode: {
              type: 'Value',
              value: 9000,
            },
            swissZipCodeAddOn: {
              type: 'Value',
              value: '00',
            },
            swissZipCodeId: {
              type: 'Value',
            },
            country: {
              type: 'Value',
              value: {
                countryNameShort: 'CH',
              },
            },
          },
          typeOfHouseholdCode: {
            type: 'Value',
            value: '1',
          },
          movingDate: {
            type: 'Value',
          },
          dwellingInformation: {
            type: 'Masked',
          },
        },
        reportingMunicipalityCantonAbbreviation: {
          type: 'Value',
          value: 'TE',
        },
        reportingMunicipalityName: {
          type: 'Value',
          value: 'Test St. Gallen',
        },
        residences: {
          type: 'Value',
          value: [1],
        },
        personStatus: 0,
        hasLock: {
          type: 'Value',
          value: '0',
        }
      },
    ],
  },
};
